### ISSUE TITLE
Keybind on Dash button doesn't work after changing spec

### ISSUE THREAD

**Issue by Damari80** [NumyAddon/TalentTreeTweaks#18]
Hi Numynum,
I have a wierd interaction on my UI. only when TTT is enabled. The spells (regardless of spell and spec) that I have keybound to dash on my first actionbar do not work. I get no error message from bugsack however. This happens only on my priest and only when TTT is enabled and after I change spec. 
After a UI reload this is fixed, but i don't want to reload the UI everytime I respec.
My other characters use the same addons, but don't have this problem.
Is this a known issue?
Thans a lot in advance

**Comment by Numynum** [comment]
Does this also happen if you're next to a training dummy, reload ui, respec, and press your keybind?

What action do you have bound to dash? A macro, a regular spell, an item?

There was a similar issue in the past, but that one was resolved quite a while ago

**Comment by Damari80** [comment]
It happens alwyas, not only when I am am next to a dummy. 
My keybinding on dash a normal offensive spells, like mind sear and Power Word: Solace.
