### ISSUE TITLE
[1.8.2] Frame drops

### ISSUE THREAD

**Issue by Discomanco** [NumyAddon/TalentTreeTweaks#23]
With the addon enabled, I'm getting lag spikes of about .5 seconds every 10-15 seconds.  
This might be related to #15, but I don't know what they used to debug to find the cause.  
This happens both in open world, dungeons and raids, where it is highly problematic.

Without TTT:
https://gyazo.com/34139ea9bc62157a599e0b80f0e3a2a6

With TTT (First spike after 15s, after enabling addon):
https://gyazo.com/06baf3d23718621a57cbb40aa26c483d

Happens significantly less with Clickable Export Strings option disabled, but it is still present

**Comment by Numynum** [comment]
The addon does some amount of work for every chat message it finds, most of that is now disabled by default (with an option to re-enable it again)
