### ISSUE TITLE
[ClickableExportStringsInChat] Can't link in Chat

### ISSUE THREAD

**Issue by Dathwada** [NumyAddon/TalentTreeTweaks#24]
Version: TalentTreeTweaks-v1.9.7
All AddOns disabled

If there is an export string in chat, I can't post it in chat with shift + left click as described by the tooltip.

ClickableExportStringsInChat.lua line 145 - 154:
```lua
if IsShiftKeyDown() then
    if "LeftButton" == button and self.talentBuildLinksSupported then
        local fixedLink = GetFixedLink(text:gsub('garrmission:TalentTreeTweaks', 'talentbuild'));
        ChatEdit_InsertLink(fixedLink);
        return;
    else
        Util:CopyText(exportString, L['Talent Loadout String']);
        return;
    end
end
```

My wild guess is that it has something to do with `self.talentBuildLinksSupported`.
It is never set and it isn't in the SavedVariables.

![grafik](https://github.com/NumyAddon/TalentTreeTweaks/assets/57680823/44fa5e28-f958-437d-8ece-10ebd9d0006a)

**Comment by Numynum** [comment]
fixed in next update
