### ISSUE TITLE
Suggestion: Change the row gate numbers to count extra points.

### ISSUE THREAD

**Issue by Kanegasi** [NumyAddon/TalentTreeTweaks#25]
When the option for "x more points required" is enabled, the gate numbers continue counting down so you get a negative number:

![image](https://github.com/NumyAddon/TalentTreeTweaks/assets/2686302/f893d444-a61d-4eb6-849e-560972d0558a)

Instead, after 0 is reached to unlock the row, could you force the number to instead count how many extra points are above the gate?

For example, ret paladin class tree (left) requires you spend 8 points in the first four rows to unlock the first gate. As you spend, the number counts down. when it reaches 0, the gate opens and you can now spend points on row five and below. If I spend no more points in the first four rows, the number should stay at 0. If I spend another point in the first four rows, the number should turn green and now show 1. I spend another point up there, the green number is now 2.

![244882993-f893d444-a61d-4eb6-849e-560972d0558a](https://github.com/NumyAddon/TalentTreeTweaks/assets/2686302/1da41d85-a944-4808-b266-e7ba31412e80)

I find it frustrating trying to remember where my extra points are. The shift cascade relearn is a godsend but this visual indicator would help immensely.

**Comment by Numynum** [comment]
I made it a little differently than suggested, but I liked the idea 🙂
