### ISSUE TITLE
Cast bar is missing when i enter the combat.

### ISSUE THREAD

**Issue by Alex190287** [NumyAddon/TalentTreeTweaks#26]
So  since i started using this addon im having  some minor problems. It started on some specific bosses like Assault of the Zaqali or Zskarn  or  last boss in Neltarus. When ever i picked up an item from the ground (rock-trap-treasure) and as soon as i got extra action bar to use i would get an lua error and my cast bar would be gone. I tried using weak aura for cast bar and im having same problem. Now problem is here when ever i switch talents and i enter the combat (it happens like 50% of the time ). No idea how to check if addons are having some kind of conflict cos i know few people who use the same addon but they have no problems.
I have taint log if that helps in any way

6/14 16:08:13.974  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:13.974  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:13.974      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:13.974      Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:16.809  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:16.809  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:16.809      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:16.809      Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:18.743  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:18.743  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:18.743      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:18.743      Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:20.061  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:20.061  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:20.061      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:20.061      Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:21.342  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:21.342  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:21.342      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:21.342      Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:22.910  Interface/FrameXML/CastingBarFrame.lua:268
6/14 16:08:22.910  An action was blocked in combat because of taint from TalentTreeTweaks - PlayerCastingBarFrame:SetShown()
6/14 16:08:22.910      Interface/FrameXML/CastingBarFrame.lua:78 PlayerCastingBarFrame:UpdateShownState()
6/14 16:08:22.910      Interface/FrameXML/CastingBarFrame.lua:268

**Comment by Numynum** [comment]
seems there's something weird about your setup, since PlayerCastingBarFrame should have nothing to do with the ExtraActionButtonFrame

can you get an extra action button out of combat somewhere, and run a few chat commands, and see what the output is?

`/dump ExtraActionButton1:GetParent():GetName()`
`/dump ExtraActionBarFrame:GetParent():GetName()`
`/dump ExtraActionBarFrame:GetParent():GetParent():GetName()`
`/dump PlayerCastingBarFrame:IsProtected()`
`/run local f;function f(a,b)return a:GetParent()==UIParent and b or f(a:GetParent(),b+1)end print(f(ExtraActionButton1,0),f(PlayerCastingBarFrame,0))`

there's a big chance that I won't be able to help resolve the issue though, since it seems to be quite rare

**Comment by Alex190287** [comment]
Hey. Thanks for quick  response. I started getting same lua error more often now. I started loosing castbar when i enter combat. It doesn't happen only on those 3 fights anymore.   Just entering any combat can trigger  the problem and my cast bar is gone. But i noticed something. It has much higher chance to happen when i switch my talents.  So im not even sure if it has to do anything with extra action button anymore. 

I did what you asked but not sure how to check what happens when i enter those chat commands. So ill just link my chat.
Dump: value=ExtraActionButton1:GetParent():GetName() [1]="ExtraActionBarFrame"

Dump: value=ExtraActionBarFrame:GetParent():GetName() [1]="ExtraAbilityContainer"

Dump: value=ExtraActionBarFrame:GetParent():GetParent():GetName() [1]="UIParent"

[20:14:54] Dump: value=PlayerCastingBarFrame:IsProtected()
[20:14:54] [1]=true,
[20:14:54] [2]=false

And the last one is 2 0

**Comment by Numynum** [comment]
thanks for the info, I was indeed looking just for the chat output 🙂 

can you try a few more things for me
`/dump PlayerCastingBarFrame:IsProtected()`
right after logging in, before touching the talent tree or anything like that. With, and without TTT enabled

if it shows [1]=false, [2]=false, then try again after changing around your talents

if it shows [1]=true with TTT disabled, then try disable all addons
if it turns into [1]=false, then enable addons again, until you find the one that turns it from false, to true


basically, if you get `[1]=true`, it means that for some reason, a protected frame or button got attached to your cast bar (which should never happen); and somewhere down the road, TTT spreads taint into the cast bar's show/hide function
normally this is fine, as the frame should not be protected (which you can tell, by it posting `[1]=false` in chat)

our goal here, is to find out what addon or setting is turning it to `[1]=true` 🙂 

if it shows [1]=true, even with all addons disabled, there's a few more debugging things that could help:
`/dump PlayerCastingBarFrame:GetNumChildren()`
if it's more than 1, then type `/tinspect {PlayerCastingBarFrame:GetChildren()}` and make a screenshot of the resulting popup
it should look something like this
![image](https://github.com/NumyAddon/TalentTreeTweaks/assets/17293527/6ce3699d-2f7f-4d7c-809a-b9c1494968aa)

**Comment by Alex190287** [comment]
So i tried with and without TTT and i would get 1 false  and 2 false.
After changing talents its still false
With all addons disabled its still false

/dump PlayerCastingBarFrame:GetNumChildren()  is showing as 1

So i have no idea what is  happening and i don't want to waste more of your time. Im sure you are busy and i want to thank you for at least trying to help me.
