### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Squimbert** [NumyAddon/TalentTreeTweaks#33]
[ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'PickupSpell()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `PickupSpell'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentButtonTemplates.lua"]:376: in function <...redTalentUI/Blizzard_SharedTalentButtonTemplates.lua:372>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Numynum** [comment]
Known issue which isn't possible to resolve; at least it only happens in combat
