### ISSUE TITLE
Window doesn't scale

### ISSUE THREAD

**Issue by rTiGd2** [NumyAddon/TalentTreeTweaks#34]
If you're so addicted that you play on a laptop when away from home, you have to adjust the global UI scale to see the talent window (but then can't read any text in the game)

**Comment by Numynum** [comment]
You should be able to simply CTRL+scroll to make it smaller, is that not working?

**Comment by rTiGd2** [comment]
I'm a moron, I didn't see that in the addon description - Read it at least twice. Sorry, working perfectly (great addon by the way, thank you for putting the time into it)
