### ISSUE TITLE
Option to change default dragonriding talent

### ISSUE THREAD

**Issue by zeenk** [NumyAddon/TalentTreeTweaks#36]
Currently lightning rush gets auto purchased in pre patch but I'd like to have Whirling surge instead, would be nice if we could get an option to pick between the two like you can with auto ride along. thx

**Comment by Numynum** [comment]
I was planning this, but unfortunately didn't find the time yet
but it's on the list 🙂

**Comment by Xorag** [comment]
+1 would appreciate this, i have the compulsive need to hit this every time i mount up for some reason

**Comment by Numynum** [comment]
latest release includes this 👍

**Comment by zeenk** [comment]
Awesome, thanks!
