### ISSUE TITLE
Hero Talents move left after opening TalentsFrame

### ISSUE THREAD

**Issue by DennisRas** [NumyAddon/TalentTreeTweaks#37]
When you open your TalentsFrame the Hero Talents are shifted to the left after a split second.
I understand there are numbers on the side of the right tree, but there must be a better way? 😛 

Without addon enabled:
![image](https://github.com/user-attachments/assets/0c895fa9-2785-47cb-b939-38ded69ca322)

With addon enabled:
![image](https://github.com/user-attachments/assets/d6170e36-0491-4a8e-9fae-99ab450bd4fb)

**Comment by DennisRas** [comment]
Would it be possible to resize the gates so they don't reach the Hero frame?
They are pretty big after all, but that's obviously my own opinion.

On a sidenote, disabling the gates will keep them visible until reload.

![image](https://github.com/user-attachments/assets/3eb318c6-a280-4618-9c7e-2f0c85f8d652)

**Comment by DennisRas** [comment]
Or maybe another crazy idea: If gates are enabled, move to the other side on the right ?

**Comment by Numynum** [comment]
They are intentionally identical to the default ui gates (except for having an extra number, and being semi transparent)
I don't intend to resize or move them

**Comment by Numynum** [comment]
Gate visibility persisting on disable is something I'll check and fix next week 👍

**Comment by Numynum** [comment]
Frankly, it's simpler to just shift the hero frame a bit
it shifts around depending on the class/spec already anyway ^^
