### ISSUE TITLE
Two GUI issues

### ISSUE THREAD

**Issue by jungheeMW** [NumyAddon/TalentTreeTweaks#38]
1. In the "DragonRiding Auto Purchase" tab, The "Toggle Skyriding UI" button does nothing when clicked. Also, the tab should probably be renamed to "Skyriding Auto Purchase" to be consistent with the new name.
<img width="457" alt="button does nothing" src="https://github.com/user-attachments/assets/6f951d14-bd3c-41b1-83ed-105dfabc494d">

2. In the "Export Loadouts" tab, the Enable/Disable checkbox is inverted. Not checking Enable will enable the feature, while checking Enable will disable "Export on Right-Click".
<img width="467" alt="inverted enable causes disable" src="https://github.com/user-attachments/assets/9d385bf4-fe5a-44ba-9d9c-80fee6c7ae25">

**Comment by Numynum** [comment]
2nd issue is first, 1st issue I couldn't find what might be going wrong, it's working fine on my end 🤔

**Comment by jungheeMW** [comment]
I disabled all addons except TTT. 1st issue still persists. I'm unsure of cause. Do you think it has to do with UI scaling settings? My WoW is windowed, 1080p, UI scale 100%.

Also, I think it would be nice to rename DragonRiding to Skyriding to be consistent with the new naming scheme.

**Comment by Numynum** [comment]
the renaming will happen soon-ish, I'm trying to deal with everything that's breaking first 😀 

1st issue is rather strange, I'm doing the exact same thing as what blizzard does in the mount journal UI; does that work for you?
![image](https://github.com/user-attachments/assets/4aa12cfa-6870-4fca-9807-f3d5fead16cd)

**Comment by jungheeMW** [comment]
Thank you, and I'm sorry for nagging you about it 😅

Yes, that button works as usual for me when I press it. My current theory is:
1. Blizzard limits the amount of UI windows you can have on your screen at a time (auction house, spellbook, talents, etc.), exceeding the limit will force-close a previous window to make space for the new one, since UI windows cannot overlap in WoW by default.
2. The amount of windows you can have open is determined by your screen resolution and the size of the UI window (you can have the macros window open as well as the minimized spellbook, but not the macros window and an enlarged spellbook)
3. Certain windows accessed with the Esc key cannot be force closed, this includes the addon list, and the Options panel.
4. TTT is tied to the Options panel (in the Addons tab), and thus, it cannot be force closed. Therefore, if the screen does not have enough real estate to open the skyriding panel, the action will fail.

**Comment by Numynum** [comment]
Ooooh, ofc, you're right (though I don't think resolution has an impact)
I'm using https://www.curseforge.com/wow/addons/no-auto-close to avoid that nonsense, so I hadn't noticed it being an issue
should be possible to bypass that restriction, though if it's ugly, I might end up removing that button tbh
