### ISSUE TITLE
auto-close addons windows when opening talents/spellbook

### ISSUE THREAD

**Issue by artazika** [NumyAddon/TalentTreeTweaks#39]
Hello! When I opening talent or spell book any addon windows (for example WA) auto closing after TWW prepatch.
Is it possible to make disable this and make an option for that?

**Comment by Numynum** [comment]
installing [NoAutoClose](https://www.curseforge.com/wow/addons/no-auto-close) with [BlizzMove](https://www.curseforge.com/wow/addons/blizzmove) resolves this, I have no plans to implement something similar in this addon 🙂
