### ISSUE TITLE
Feature Suggestion - leveling talent order

### ISSUE THREAD

**Issue by lubitow** [NumyAddon/TalentTreeTweaks#4]
It would be cool if the addon detected that you are below max level if you imported a string it would show you the order to apply the next few talents like:

https://github.com/mikeacjones/TalentSequence2

From Classic

**Comment by Numynum** [comment]
I've had this idea for a while now, but I'm not sure how to approach it yet
it's more difficult since there is no talent order in the wowhead calculator (and presumably not for icyveins either)
and the exported link ingame doesn't show any order either; all I could do right now, is highlight the talents you should take, but not in any specific order

**Comment by mateutek** [comment]
@Numynum Zygor does it like you describe it add +1/+2 on the right corner of the talent.
I was thinking of implementing an addon myself, but looking through the curseforge came across this addon.
I can try to implement it somehow. I'm a programmer but haven't touched LUA too much. If you can give me some guides or documentation to follow i can try to implement this.

**Comment by Numynum** [comment]
@mateutek I'm happy to collaborate on something like this, though from my perspective it'd make more sense to implement it in https://github.com/NumyAddon/TalentLoadoutManager
that addon already allows importing a max-lvl build, but its visualization isn't fully integrated into the talent tree, and there's no talent order; it just tries to learn talents in effectively random order

It could use an "auto learn on leveling" feature too 🤔 (similar to how TTT autolearns dragonflying talents)

I'm not sure if there's enough people that care about specific lvling order, to really put all the required work in for that; but a visual face-lift, and autolearn feature would probably do wonders 🙂

**Comment by mateutek** [comment]
Sure, i will take a look at the other one, will fork it and try to figure sth out on my own.
In the mvp i would just show what talents still need to be selected.
Then maybe the auto-lvl

**Comment by Numynum** [comment]
https://www.curseforge.com/wow/addons/talent-loadout-manager and https://www.curseforge.com/wow/addons/talenttree-viewer now support leveling builds 🙂
