### ISSUE TITLE
Talent loadout tooltip issue

### ISSUE THREAD

**Issue by TaikooS** [NumyAddon/TalentTreeTweaks#40]
The text and nodes preview in the loadout tooltip will shrink infinitely when hovering. No Lua error was shown.

Here's my screen record:
https://imgur.com/a/pMQ4IX1

**Comment by TaikooS** [comment]
I just discovered it's caused by another addon [Multilanguage](https://www.curseforge.com/wow/addons/multilanguage). 

Sorry if it confused you.

**Comment by Numynum** [comment]
ah good, I was indeed very confused :D
