### ISSUE TITLE
Add Project ID to TOC file

### ISSUE THREAD

**Issue by jungheeMW** [NumyAddon/TalentTreeTweaks#42]
Hello, could you add the following line to the TOC file? It allows 3rd party addon managers to download and update the addon by pulling from CurseForge. The ID in the line is your project ID on Curseforge.
`## X-Curse-Project-ID: 678792`

**Comment by Numynum** [comment]
It's in there already

**Comment by jungheeMW** [comment]
Apologies, the issue I found seems to be a bug with WowUp. But thank you for your time.
