### ISSUE TITLE
LUA error in combat + potential CurseForge issue

### ISSUE THREAD

**Issue by jungheeMW** [NumyAddon/TalentTreeTweaks#45]
Two problems:

1. While in combat, TTT sometimes produces the following LUA error
```
1x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'MultiBarRightButton4:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:488: in function `UpdatePressAndHoldAction'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:554: in function `Update'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:506: in function `UpdateAction'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:991: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:982>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```
2. Previously in #42 I mentioned that 3rd party addon managers were having trouble detecting your addon. Now it seems like even the Curseforge App is having trouble too. If your addon is downloaded manually and then unzipped into the Addons folder, Curseforge cannot detect it no matter how many times you attempt a Rescan of the Addons folder. If TTT is downloaded via the Curseforge App, and a Rescan of the folder is attempted, the addon will show as "Modified" and the CF App will prompt for a reinstall.

Could you look into it? It's possible that it might be a Curseforge issue as some other addons seem to also share the same problem.

**Comment by Numynum** [comment]
For the 1st one:
could you check if it's due to https://github.com/NumyAddon/TalentTreeTweaks/issues/44?
if not:
do you play with default actionbars, or an addon?
Can you enable [taintlog](https://warcraft.wiki.gg/wiki/CVar_taintLog), and upload it next time you encounter the error?
if you manage to find a way to reliably reproduce it, I'm all ears. Personally I play with elvui, which is pretty much immune to all of these issues, which makes them hard to find and fix (same goes for bartender and addons using the same tech)

For the CF issue.. I'm not sure where I'd even start tbh, frankly I think it'd be better if you were to create a support ticket @ CF, especially if you have this issue with multiple addons

**Comment by jungheeMW** [comment]
It might be related to #44, but in my case, my action bars do not lock up, I only get a LUA error upon entering combat for the first time upon login. I'm using Dominos for my action bars.

However, I discovered a different LUA error while trying to replicate the steps from #44. If I get on a skyriding mount, the following LUA error appears after I enter combat. If I enter combat without getting on a mount, I get the error above https://github.com/NumyAddon/TalentTreeTweaks/issues/45#issue-2485032335.
```
1x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'PetActionBar:SetShownBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetShownBase'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:330: in function `UpdateVisibility'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:324: in function `Hide'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:172: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:119>
[string "=[C]"]: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:83: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```
Here are two taint logs
[taint1.log](https://github.com/user-attachments/files/16739435/taint1.log)
[taint2.log](https://github.com/user-attachments/files/16739436/taint2.log)

**Comment by Numynum** [comment]
Dominos uses the same tech as the default UI for actionbars, so that's useful to know
Also good to know the error doesn't seem to be _breaking_ anything as such

**Comment by Numynum** [comment]
from the taintlog, it looks like it was caused by the same problem as #44, please check if it's still happening with the latest version

**Comment by jungheeMW** [comment]
All clear, no LUA errors using [v1.12.14](https://github.com/NumyAddon/TalentTreeTweaks/releases/tag/v1.12.14)
