### ISSUE TITLE
Frequently getting error when trying to use spells and can't cast until I reload

### ISSUE THREAD

**Issue by AdamKamondi** [NumyAddon/TalentTreeTweaks#46]
I've had this bug since dragonflight... tried fully uninstalling the addon and every saved variable related to it, but I still keep getting it.
It just happens infrequently but often and usually at the worst moments, like on the first pull of a dungeon.

As soon as I press a hotkey for a spell (some spells work some don't) I get the LUA error and I can't cast most of my spells until I reload.

I just got the error when trying to use Incarnation: Chosen of Elune and after that any spells I pressed besides Moonfire I got the error - but on Moonfire it didn't... It's not related to a spell being a talent, because I couldn't cast Wrath.

Just today I got the error like six times. For a while it's working, I enter my 3th dungeon or battleground or w/e and suddenly the error occours and I have to reload.

`50x [ADDON_ACTION_FORBIDDEN] AddOn 'TalentTreeTweaks' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function UseAction
[string "@FrameXML/SecureTemplates.lua"]:364: in function handler
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function ActionButtonDown'
[string "ACTIONBUTTON4"]:2: in function <[string "ACTIONBUTTON4"]:1>`

**Comment by Numynum** [comment]
I haven't been able to trigger this at all, but that's also because I use elvui. elvui and bartender action bars seem to be mostly immune to this problem :/
but also when trying to trigger any issue with default UI, I just haven't been able to get any error to happen

can you try to play with [taintlog](https://warcraft.wiki.gg/wiki/CVar_taintLog) for a bit, and send me the log when it next happens?
any other info of what you were doing might also be helpful, things like inspecting other players, changing talents, respeccing, etc

I did make some changes with TWW that should've helped some issues; I was able to trigger taint error a bit during beta, but never anymore after the changes I made 🤔 

blizzard _is_ also making some changes in 11.0.5 that might help reduce action bar issues; but whether it will help this problem, I cannot say without more info sadly

**Comment by AdamKamondi** [comment]
Sure, just now I got a different error, but it's the same symptom - can't use most of my action bars. I logged in, switched from PvP talents to my open world talents, started a quest and immediately got the error when trying to cast Wrath.

Here is the taintlog:

`8/30 11:48:08.312  Global variable ON_BAR_HIGHLIGHT_MARKS tainted by TalentTreeTweaks - Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:58 ClearOnBarHighlightMarks()
8/30 11:48:08.312      Interface/AddOns/Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:513 Frame:
()
8/30 11:48:08.312      Interface/AddOns/Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:733
8/30 11:48:08.312  Execution tainted by TalentTreeTweaks while reading ON_BAR_HIGHLIGHT_MARKS - Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:626 MultiBarBottomRightButton6:UpdateSpellHighlightMark()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:534 MultiBarBottomRightButton6:Update()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:506 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton6:SetAttribute()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:488 MultiBarBottomRightButton6:UpdatePressAndHoldAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:554 MultiBarBottomRightButton6:Update()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:506 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton1:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer1:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton2:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer2:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton3:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer3:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton4:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer4:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton5:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer5:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton6:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer6:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton7:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer7:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton8:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButtonContainer8:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:209 MultiBarBottomRight:UpdateShownButtons()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:510 MultiBarBottomRightButton6:UpdateAction()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:991
8/30 11:48:08.312  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
8/30 11:48:08.312  An action was blocked in combat because of taint from TalentTreeTweaks - MultiBarBottomRightButton9:SetShown()
8/30 11:48:08.312      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:206 MultiBarBottomRight:UpdateShownButtons()`

**Comment by AdamKamondi** [comment]
I indeed use the default UI, no ElvUI or Bartender.
Strange thing is with this petBar error is that I'm a druid - so I don't even have a pet.

Here is the bugsack error:
`6x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'PetActionBar:SetShownBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetShownBase'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:330: in function `UpdateVisibility'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:324: in function `Hide'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:172: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:83: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
`

**Comment by Numynum** [comment]
interesting..
does disabling the `Copy SpellID on hover` module help?

**Comment by AdamKamondi** [comment]
I will try that now.

**Comment by AdamKamondi** [comment]
I'm glad to report that since disabling the module I haven't encountered the problem! I got a few LUA errors from the addon, but none of those caused any kind of problems.

Here are a few of the errors I got:

```
10x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'MultiBarBottomRightButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:194: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:346: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:1179: in function <FrameXML/ActionButton.lua:1176>
[string "=[C]"]: ?
```

and 


5x [ADDON_ACTION_BLOCKED] AddOn 'TalentTreeTweaks' tried to call the protected function 'MultiBarBottomLeftButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:196: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:351: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:809: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:200: in function <FrameXML/ActionButton.lua:197>

```
Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

Neither of these caused any hotkey or other kinds of issues, so I'm happy! :)

**Comment by Numynum** [comment]
those I do see sometimes, but for me it always blames Elvui, interesting 🤔 
I'll take a look at what's going on with that module then.. it's very strange that it affects the spellbook in that way

**Comment by Numynum** [comment]
I've made some changes, would you mind enabling the module again to see if that fixed the issues that blocked your actionbar? ^^

**Comment by AdamKamondi** [comment]
I updated the addon, haven't enabled the module yet, but I got a new error as soon as I entered a BG and switched talents:

```
9/3 15:08:33.331  Global variable ON_BAR_HIGHLIGHT_MARKS tainted by TalentTreeTweaks - Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:58 ClearOnBarHighlightMarks()
9/3 15:08:33.331      Interface/AddOns/Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:513 Frame:OnIconEnter()
9/3 15:08:33.331      Interface/AddOns/Blizzard_PlayerSpells/SpellBook/Blizzard_SpellBookItem.lua:733
9/3 15:08:33.331  Execution tainted by TalentTreeTweaks while reading ON_BAR_HIGHLIGHT_MARKS - Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:62 GetOnBarHighlightMark()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:626 ActionButton12:UpdateSpellHighlightMark()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:534 ActionButton12:Update()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:506 ActionButton12:UpdateAction()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBarController/Mainline/ActionBarController.lua:168 ActionBarController_UpdateAll()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBarController/Mainline/ActionBarController.lua:66
9/3 15:08:33.331  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:1335 UpdateFlyout()
9/3 15:08:33.331  An action was blocked because of taint from TalentTreeTweaks - UseAction()
9/3 15:08:33.331      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:342 handler()
9/3 15:08:33.331      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:667 PerformAction()
9/3 15:08:33.331      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:681 OnActionButtonClick()
9/3 15:08:33.331      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:723 SecureActionButton_OnClick()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:100 TryUseActionButton()
9/3 15:08:33.331      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:135 ActionButtonDown()
9/3 15:08:33.331      ACTIONBUTTON10:2
9/3 15:08:43.801  Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:1335 UpdateFlyout()
9/3 15:08:43.801  An action was blocked because of taint from TalentTreeTweaks - UseAction()
9/3 15:08:43.801      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:342 handler()
9/3 15:08:43.801      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:667 PerformAction()
9/3 15:08:43.801      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:681 OnActionButtonClick()
9/3 15:08:43.801      Interface/AddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:723 SecureActionButton_OnClick()
9/3 15:08:43.801      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:100 TryUseActionButton()
9/3 15:08:43.801      Interface/AddOns/Blizzard_ActionBar/Mainline/ActionButton.lua:135 ActionButtonDown()
9/3 15:08:43.801      ACTIONBUTTON10:2

```

This is **without** the module enabled.

I'll enable it now.

**Comment by Numynum** [comment]
I guess the module wasn't to blame after all.. O.o
You can leave it on or off, it seems to not really make any difference

but now I'm not sure what'd be causing this..
is there anything of interest in the taintlog right above those lines?

I'm going to try to find a nuclear option to fix this issue, but no guarantees I can get it to work (looking at the timestamps in the taintlog, it seems unlikely actually :/)
out of curiosity, do you have "flyout" spells on your bar (like those expandable spell groups with polymorphs, pet whistles, etc), if so, does removing those from your bar help at all? 🤔

**Comment by AdamKamondi** [comment]
Here is a screenshot of my current UI:

![WoWScrnShot_090324_152829](https://github.com/user-attachments/assets/3501631d-2aa7-4da8-9d57-8f082812057d)

**Comment by AdamKamondi** [comment]
If you'd like you can add me on Discord: tortellion
I'd be happy to work with you / provide any help I can - I'm a programmer aswell, tho I haven't dabled much in LUA yet.

**Comment by Numynum** [comment]
Good to know, that might speed up debugging 👍

**Comment by Numynum** [comment]
should no longer occur since 11.0.5
