### ISSUE TITLE
Feature Request: Compare talent trees without inspecting

### ISSUE THREAD

**Issue by DavidPHH** [NumyAddon/TalentTreeTweaks#49]
Hi, I think it'd be nice if there was a way you could paste in a talent tree code and compare it to your current talents (or vs another code). Similar to how the differences show when inspecting someone.

**Comment by Numynum** [comment]
you can do (most of) that already with [Talent Tree Viewer](https://www.curseforge.com/wow/addons/talenttree-viewer) 🙂
