### ISSUE TITLE
Talent tree frame sometimes goes out of frame

### ISSUE THREAD

**Issue by zeenk** [NumyAddon/TalentTreeTweaks#51]
Not that big of a deal as it resets itself if u just re-open it but I noticed that if you have the talent frame open while teleporting somewhere it then goes out of frame on next open, easiest to test this on a mage and just teleport between places

https://github.com/user-attachments/assets/9633c233-93a0-48a1-82a7-c7c37b545e3c

**Comment by Numynum** [comment]
I'm guessing you have an addon that makes the frame moveable, which one?
and does this happen with all addons disabled except for TTT?
and stops happening if you have all your addons enabled except TTT? 🤔

**Comment by zeenk** [comment]
I tested with only TTT before and it also pushed it to the left but didn't fully go out of frame then like it did in the video, if u want to test it urself just have the talent frame open and then use ur hearthstone or something, mage is best so u can test without cd, I think I have the scale set to 0.85 in TTT settings if it matters? Going to bed now so won't be able to respond for a bit if u have further questions but I hope it helps so u can replicate it, also I'm on 1080p 75% ui render scale

**Comment by zeenk** [comment]
Ok tested now without any addon enabled and it still pushes it to the left so I'm closing this as it seem to be a Blizzard issue ^^

https://github.com/user-attachments/assets/63c7f767-b434-4d10-9f24-166e14083d83
